---
- name: Scale appx-api deployment in Kubernetes
  hosts: minikube
  tasks:
    - name: Scale deployment
      k8s:
        name: appx-api-deployment
        namespace: default
        replicas: 3
        state: present
