---
- name: Scale appx-api deployment in Kubernetes
  hosts: minikube
  tasks:
    - name: Scale deployment
      k8s:
        name: appx-api-deployment
        namespace: default  
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          spec:
            replicas: 3  
      register: result

    - debug:
        var: result
