---
- name: Scale appx-api deployment in Kubernetes
  hosts: minikube
  become: yes
  tasks:
    - name: Scale the deployment
      command: /usr/local/bin/kubectl scale deployment appx-api-deployment --replicas=3
      args:
        chdir: /home/produccion/TP-Grupo01-Credicoop/APPx-API/Minikube
