---
- name: Scale appx-api deployment in Kubernetes
  hosts: minikube
  become: yes
  tasks:
    - name: Scale the deployment
      command: kubectl scale deployment appx-api-deployment --replicas={{ desired_replicas }}
      args:
        chdir: /home/produccion/TP-Grupo01-Credicoop/APPx-API/Minikube  
      vars:
        desired_replicas: 3  
