- name: Scale appx-api deployment in Kubernetes
  hosts: minikube  
  become: yes
  tasks:
    - name: Ensure kubectl context is correct
      command: /usr/local/bin/kubectl config use-context minikube
      args:
        chdir: /home/produccion  

    - name: Scale the deployment
      command: /usr/local/bin/kubectl scale deployment appx-api-deployment --replicas=3
      args:
        chdir: /home/produccion/TP-Grupo01-Credicoop/APPx-API/Minikube
