version: '3.1'

services:
  dbservice:
    image: postgres
    restart: always
    env_file:
      - env_variables.env 
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
