services:
  dbservice:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: g02OqC4A1sRnd2TpF6ONLRT3Qg63EHrd
      POSTGRES_DB: dbservice
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
