services:
  appx-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env_variables.env
    environment:
      POSTGRES_URL=jdbc:postgresql://dbservice:5432/${POSTGRES_DB}  
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-network

  dbservice:
    image: postgres
    env_file:
      - env_variables.env  
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
