version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_INNODB_BUFFER_POOL_SIZE: 64M
      MYSQL_MAX_CONNECTIONS: 20
      MYSQL_TMP_TABLE_SIZE: 16M
      MYSQL_INNODB_LOG_BUFFER_SIZE: 8M
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1.5G  # Aumentar límite a 1.5 GB
        reservations:
          memory: 1G  # Reservar 1 GB

  mediawiki:
    build: .  # Construye la imagen a partir del Dockerfile en el directorio actual
    environment:
      MEDIAWIKI_DB_TYPE: ${MEDIAWIKI_DB_TYPE}
      MEDIAWIKI_DB_HOST: ${MEDIAWIKI_DB_HOST}
      MEDIAWIKI_DB_NAME: ${MEDIAWIKI_DB_NAME}
      MEDIAWIKI_DB_USER: ${MEDIAWIKI_DB_USER}
      MEDIAWIKI_DB_PASSWORD: ${MEDIAWIKI_DB_PASSWORD}
      MEDIAWIKI_SITE_NAME: ${MEDIAWIKI_SITE_NAME}
      MEDIAWIKI_LANGUAGE_CODE: ${MEDIAWIKI_LANGUAGE_CODE}
      MEDIAWIKI_DEFAULT_SKIN: ${MEDIAWIKI_DEFAULT_SKIN}
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - db
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php  # Asegúrate de que la ruta sea correcta
    command: >
      /bin/bash -c "
      php /var/www/html/maintenance/update.php && 
      apache2-foreground"

volumes:
  db_data:
