version: '3.8' # Puedes omitir esta línea si la estás usando en una versión reciente

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  mediawiki:
    image: mediawiki:1.39
    environment:
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_NAME: ${MYSQL_DATABASE}
      MEDIAWIKI_DB_USER: ${MYSQL_USER}
      MEDIAWIKI_DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "7000:80"
    depends_on:
      - db
    volumes:
      - mediawiki_data:/var/www/html

volumes:
  db_data:
  mediawiki_data:
