apiVersion: apps/v1
kind: Deployment
metadata:
  name: appx-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appx-api
  template:
    metadata:
      labels:
        app: appx-api
    spec:
      containers:
      - name: appx-api-container
        image: ronniemezzapesa/tp-credicoop:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_URL
          value: "jdbc:postgresql://192.168.232.133:5432/dbservice"  # Puedes reemplazar esto por un ConfigMap o Secret si lo deseas
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
      imagePullSecrets:
      - name: regcred
