apiVersion: apps/v1
kind: Deployment
metadata:
  name: appx-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appx-api
  template:
    metadata:
      labels:
        app: appx-api
    spec:
      containers:
      - name: appx-api-container
        image: ronniemezzapesa/tp-credicoop:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_URL
          value: "${POSTGRES_URL}"
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_PASSWORD
          value: "${POSTGRES_PASSWORD}"
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: appx-api-service
spec:
  selector:
    app: appx-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
