apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbservice
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
      - name: dbservice
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: dbservice
        - name: POSTGRES_USER
          value: postgres 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret  
              key: POSTGRES_PASSWORD
